name: 'Code Cutter Congratulator'
description: 'Creates a comment on a PR if the PR deletes more code than it adds'
inputs:
  github-token:  
    description: 'token'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
