on: [pull_request]

jobs:
  test_pr_code_delete:
    runs-on: ubuntu-latest
    name: A job to test the PR guy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test PR deleter commenter
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}